name: Test & Push Coverage
on:
  push:
    branches:
      - master
      - develop
jobs:
  test_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run Test
        run: |
          coverage run -m pytest .
      - name: Generate coverage report
        run: |
          coverage report
          coverage xml

      - name: Uploading Reports to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./coverage.xml # optional
